version: '3.4'

services:
    
    roomData:
        image: mcr.microsoft.com/mssql/server

    userData:
        image: mcr.microsoft.com/mssql/server

    studyroom.api:
        image: ${DOCKER_REGISTRY-}studyroomapi
        build:
            context: .
            dockerfile: Src/StudyRoom/StudyRoom.API/Dockerfile
    adminuser.api:
        image: ${DOCKER_REGISTRY-}adminuserapi
        build:
            context: .
            dockerfile: Src/Users/Admin/AdminUser.API/Dockerfile
    nusers.api:
        image: ${DOCKER_REGISTRY-}nusersapi
        build:
          context: .
          dockerfile: Src/Users/NUser/NUsers.API/Dockerfile
    booking.api:
        image: ${DOCKER_REGISTRY-}bookingapi
        build:
          context: .
          dockerfile: Src/Booking/Booking.API/Dockerfile
    apigateway:
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: Src/Gatteway/APIGateway/Dockerfile