version: '3.4'

services:   
    roomData:
        container_name: roomData
        ports:
            - "9007:1433"
        environment:
            SA_PASSWORD: "Staycool@99"
            ACCEPT_EULA: "Y"
    userData:
        container_name: userData
        ports:
            - "9008:1433"
        environment:
            SA_PASSWORD: "Hanc@1208"
            ACCEPT_EULA: "Y"
    bookingData:
        container_name: bookingData
        ports:
            - "9009:1433"
        environment:
            SA_PASSWORD: "Staycool@99"
            ACCEPT_EULA: "Y"

    studyroom.api:
        container_name: studyroomapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:StudyRoomDbContext=Server=roomData;Database=RoomData;User Id=sa;Password=Staycool@99;"
        depends_on:
            - roomData
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8002:80"
    adminuser.api:
        container_name: adminuserapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:AdminUserDBContext=Server=userData;Database=UserData;User Id=sa;Password=Hanc@1208;"
        depends_on:
            - userData
        ports:
            - "8003:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    nusers.api:
        container_name: nuserapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:NUserDBContext=Server=userData;Database=UserData;User Id=sa;Password=Hanc@1208;"
        depends_on:
            - userData
        ports:
            - "8004:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    booking.api:
        container_name: bookingapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:BookingDBContext=Server=bookingData;Database=BookingData;User Id=sa;Password=Staycool@99;"
        depends_on:
            - bookingData
        ports:
            - "8004:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    apigateway:
        container_name: apigateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - studyroom.api
            - nusers.api
            - adminuser.api
            - booking.api
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "7001:80"