// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyRoom.API.Data;

namespace StudyRoom.API.Migrations
{
    [DbContext(typeof(StudyRoomDbContext))]
    partial class StudyRoomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("StudyRoom.API.Model.Rooms", b =>
                {
                    b.Property<int>("SId")
                        .HasColumnType("int");
                        

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Options")
                        .HasColumnType("int");

                    b.HasKey("SId");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
